apply plugin: 'com.android.application'
apply plugin: 'realm-android'

// This part just loads the key information from an outside unversioned file
def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    signingConfigs {
        lockerRoom {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "pt.cmg.sweranker"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 4
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        debug {
            debuggable true
        }
        release {
            lintOptions {
                disable "MissingTranslation"
            }
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.lockerRoom
        }
    }

    // The usage of two flavours is meant to separate into two apps: one that only views results
    // and an admin one where I can match the degrees without cluttering the client one.
    flavorDimensions "feature"
    productFlavors {
        client {

        }
        admin {
            applicationIdSuffix ".admin"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

// This is a nasty part. I use this snippet to generate both a directory for Dagger2 classes for JUNIT and
// to run an assembleUnitTest task in order to actually create the classes
android.applicationVariants.all { variant ->
    if (variant.buildType.name == "debug") {
        def aptOutputDir = new File(buildDir, "generated/source/apt/${variant.unitTestVariant.dirName}")
        variant.unitTestVariant.addJavaSourceFoldersToModel(aptOutputDir)
        assembleClientDebug.finalizedBy('assembleClientDebugUnitTest')
        assembleAdminDebug.finalizedBy('assembleAdminDebugUnitTest')
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    // These are mostly the support and design libraries from google
    implementation 'com.android.support:support-v4:26.1.0'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support:cardview-v7:26.1.0'
    implementation 'com.android.support:recyclerview-v7:26.1.0'
    implementation 'com.android.support:support-annotations:27.0.2'
    implementation 'com.android.support:gridlayout-v7:26.1.0'
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    // Architecture components, new stuff from google
    implementation 'android.arch.lifecycle:runtime:1.0.0-alpha9'
    implementation 'android.arch.lifecycle:extensions:1.0.0-alpha9'
    annotationProcessor "android.arch.lifecycle:compiler:1.0.0-alpha9"
    // Little helper library to create a Constants-sort class to field names
    annotationProcessor 'dk.ilios:realmfieldnameshelper:1.1.1'
    // Mathematical combinatory library, so that I hadn't to implement that myself
    implementation 'com.googlecode.combinatoricslib:combinatoricslib:2.1'
    // Used to do some String juggling
    implementation 'org.apache.commons:commons-lang3:3.5'
    // Here is the Chart library
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.2'
    // All this just for the Optional... thanks google for not fully supporting Java8 after 2 years...
    implementation 'com.google.guava:guava:23.0-android'
    // Below are the Dagger2 dependencies
    implementation 'com.google.dagger:dagger:2.11'
    implementation 'com.google.dagger:dagger-android:2.11'
    implementation 'com.google.dagger:dagger-android-support:2.11'
    annotationProcessor 'com.google.dagger:dagger-compiler:2.11'
    annotationProcessor 'com.google.dagger:dagger-android-processor:2.11'
    testImplementation 'com.google.dagger:dagger:2.11'
    testAnnotationProcessor 'com.google.dagger:dagger-compiler:2.11'
    //Junit 4
    testCompile 'junit:junit:4.12'
}
